### ISSUE TITLE
Setup travis CI

### ISSUE THREAD

**Issue by binki** [benjamingr/tmp-promise#12]
It seems like #9 probably happened because nobody noticed that the tests failed in the first place. Setting up Travis CI would help with that. Please let me know if a PR for a `.travis.yml` would be accepted.

**Comment by benjamingr** [comment]
Sure, it would be accepted - even more so if you feel like setting up free open source CI for the project that'd be great.

**Comment by binki** [comment]
Because you need administrator access on the GitHub repo to add the integration, I would recommend you do it yourself instead of giving me that access ;-). I can only setup CI for my own fork. I’ll hopefully be able to write `.travis.yml` and `appveyor.yml` PRs later today and show how it works.

**Comment by silkentrance** [comment]
@benjamingr you can do it yourself, just navigate to travis-ci.org and sign on via github.

**Comment by paulmelnikow** [comment]
Hi @benjamingr I see this was closed.

I think it would be really helpful to have some CI set up!

I'd be happy to open a new PR with config for CircleCI, or to reopen #15 if you'd prefer to use Travis. Either way though, since this project lives in your own github account, you'll need to add the repo in Circle or Travis. As far as I know, there's not a way to delegate that authority on a personal repo.
