### ISSUE TITLE
Please upgrade to tmp 0.1.0

### ISSUE THREAD

**Issue by silkentrance** [benjamingr/tmp-promise#23]
Thanks for this great package.

@raszi just released a new 0.1.0 version of tmp.

And you might want to support that version, too.

Maybe we can also get rid of the extra bluebird dependency since node >= 7 has built in support for promises?

As for tmp, we have already dropped any support for node versions < 8 on *ix. For windows, it seems that we still support version 7, but this might be an oversight.

**Comment by benjamingr** [comment]
Sure, sounds good to me.

**Comment by benjamingr** [comment]
- I would rather keep the bluebird dependency as it's still safer for library usage. I hope that we'll be able to have safe "enough" promises in Node very soon(ish). Also, I'd like to use `util.promisify` but that requires Node 8. What about dropping bluebird in a few months when Node 6 usage is down and we can use `util.promisify` safely?
 - PR for tmp 0.1.0 welcome, I assume there are no breaking changes (since it's a minor) but I'm not sure about it. I'm absolutely fine not supporting Node versions lower than (or equal to) 4 since we don't support them in Node core anyway.

**Comment by benjamingr** [comment]
Also, seeing you maintain tmp now - if that would make it easier I will gladly give you collaborator access to this repo and the npm package if that helps.

Alternatively I'll happily make changes myself if I know it's safe to update and won't break things for users.

**Comment by silkentrance** [comment]
I just tested this the new version 0.1.0.

And now there is a race condition in the withFile test.

The reason for this is that in the cleanupCallback we first close and then unlink the file.

While this works just fine, the assertion in the test is run before that the unlinking takes place.

The only way I see to circumvent this is to 

```
  return module.exports.file.apply(tmp, params).then(function context(o) {
    cleanup = o.cleanup;
    fd = o.fd;
    filepath = o.path;
    delete o.cleanup;
    fn(o);
  }).finally(function () {
    try {
      fs.closeSync(fd);
      fs.unlinkSync(filepath);
    } catch (ignored) {
    }
    // let tmp clean up its internal registry of cleanup handlers
    // May not pass any arguments to cleanup() or it fails.
    if (cleanup) {
      cleanup();
    }
  });
```

**Comment by paulmelnikow** [comment]
> * I would rather keep the bluebird dependency as it's still safer for library usage. I hope that we'll be able to have safe "enough" promises in Node very soon(ish). Also, I'd like to use `util.promisify` but that requires Node 8. What about dropping bluebird in a few months when Node 6 usage is down and we can use `util.promisify` safely?

I thought I'd mention that in the time since this was written, Node 6 has reached end of life and Node 12 has been released! Many libraries are supporting 8+ to match [Node's release schedule](https://github.com/nodejs/Release#release-schedule).

Node 8 also has native async / await which is a big plus.

**Comment by benjamingr** [comment]
@silkentrance I completely forgot about this - thanks for raising this issue and for your contribution and fix. I'll craft a release.

@paulmelnikow I sure how I'd know that :] 

In related news if you'd like to contribute a PR to convert the code to util.promisify I'm game - we made it plenty fast.

**Comment by paulmelnikow** [comment]
Ha! I didn't realize you worked on Node. Nice :) I'll give it a shot if I can!

**Comment by benjamingr** [comment]
@paulmelnikow sure, just remember that we don't support multiArgs in `util.promisify` so we'd need to wrap the callback:

That is, `Promise.promisify(fn, { multiArgs: true})` can't be directly `util.promisify`d and needs to instead be something like:

```js
util.promisify((...args, cb) => fn(...args, (err, ...multipleValues) => cb(err, multipleValues)));
```
