### ISSUE TITLE
`await tmp.dir()` returns a string now.

### ISSUE THREAD

**Issue by davidmurdoch** [benjamingr/tmp-promise#29]
https://github.com/benjamingr/tmp-promise/blob/6bd19f9e42d004fc10f1dc84aa5be1045b1e543a/index.js#L25-L30

I think this is what is happening here is this:

`promisify` will always pass its promise-resolving callback function _after_ the caller's last argument. Calling `tmp-promise`'s `tmp.dir` without an `options` argument will cause `promisify` to pass its callback function as the _first_ arg (`options` here), since the first arg is also the final arg.

When `tmp.dir` is given a function as it's _first_ arg, as is done here when `options` is not provided, it uses that argument as the callback function. 

This means the callback function `tmp-promise` provides as the second argument to `tmp.dir` is never called.

**Comment by benjamingr** [comment]
Good catch, I have unpublished 2.x in the meantime since the regression is big enough in my opinion to warrant that on holiday but I've not reverted the code in master.

I can take a look when I'm back from DevDays on doing a quick fix.

I thought we had a test for this but apparently we don't - that's entirely unacceptable and is my fault, I will write one when I get back.

PR for either (and hopefully both) of those things welcome :) 

cc @paulmelnikow

**Comment by paulmelnikow** [comment]
I'll see if I can push a test!
